language: csharp
solution: openweathemap.api.test.sln
install:
  - nuget restore ./openweathemapr.api.test/openweathemap.api.test.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ./openweathemapr.api.test/openweathemap.api.test.sln
  - mono ./openweathemapr.api.test/packages/xunit.runner.console.2.2.0/tools/xunit.console.exe ./openweathemapr.api.test/openweathemapr.api.test/bin/Release/openweathemap.api.test.dll