language: csharp
solution: openweathemap.api.test.sln
install:
  - nuget restore ./openweathemapr.api.test/openweathemap.api.test.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ./openweathemapr.api.test/openweathemap.api.test.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ../openweathemapr.api.test/openweathemapr.api.test/bin/Release/openweathemap.api.test.dll